### ISSUE TITLE
upwdchg-frontend.dpkg broken

### ISSUE THREAD

**Issue by alex-dot** [cedric-dufour/upwdchg#1]
Building the debian package pulls in requirements for either `libapache2-mod-php5` or `php5-cgi` which are both apache2 packages, breaking dependency compatibility with other webserver setups, e.g. nginx+php-fpm. 

Moreover, the post-install script assumes the old-style of apache configuration directories in debian (namely `/etc/apach2/conf.d` instead of the current `/etc/apache2/site-[disabled|enabled]`), this returns an error when installing on recent debian systems.

**Comment by cedric-dufour** [comment]
Thanks for reporting those issues

Issue 1: I propose to add 'php5-fpm' as alternative (I wish I could also add PHP 7 alternatives but currently have no time to dig into it)

Issue 2: I'll adapt the script to detect new style conf (`/etc/apache2/conf-{disabled,enable}`)

Issue 3: I must get rid of that 'gsed' stuff (a 'sed' wrapper, coming from my 'gcfg' framework, that does not break hardlinks)

Does this sounds good to you ?

PS: I'm trying to keep the 'debian' stuff as generic as possible, iow. having a single branch support all reasonable Debian versions (oldstable, stable and testing)

**Comment by alex-dot** [comment]
That's perfect, it's what I had in mind. Thanks!
