### ISSUE TITLE
Password error für §-symbol in Active Directory context

### ISSUE THREAD

**Issue by alex-dot** [cedric-dufour/upwdchg#4]
Hi, 

I just realized that Microsofts AD does not accept the §-symbol in passwords (see: https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements)

This can lead to failing password resets on the backend. Therefore, we should implement a setting in the password policy settings of the frontend that checks the passwords for that (and other) symbol(s), so a descriptive error message can be presented to the user.

I'd suggest implementing it so that the administrators can define the blacklisted symbols themselves, maybe defaulting it to the §-symbol.

**Comment by cedric-dufour** [comment]
Hello,
I believe this issue is solved by commit 97cb6ff792786fee1f612d7b3877c2f80b24b46d and the introduced 'password_charset_forbidden' setting.
Best
